services:
  socket_app:
    restart: always
    build:
      context: .
      dockerfile: socketapp/Dockerfile
    container_name: socketapp
    environment:
      - REDIS_CLIENT_AUTH_DB=${REDIS_CLIENT_AUTH_DB}
      - REDIS_CLIENT_AUTH_PORT=${REDIS_CLIENT_AUTH_DB_PORT}
      - REDIS_ADMIN_DB=${REDIS_ADMIN_DB}
      - REDIS_ADMIN_PORT=${REDIS_ADMIN_DB_PORT}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - API_NAME=${API_NAME}
      - API_PORT=${API_PORT}
    volumes:
      - app_agentik_data:/usr/src/app
      - app_data:/home/quart/instance/apps

  rate_limit_redis:
    image: redis:latest
    container_name: ${REDIS_RATE_LIMIT_DB}
    command: ["redis-server", "--port", "4379", "--appendonly", "yes"]
    volumes:
      - rate_limit_data:/data 

  client_auth_redis:
    image: redis:latest
    container_name: ${REDIS_CLIENT_AUTH_DB}
    command: ["redis-server", "--port", "6369", "--appendonly", "yes"]
    volumes:
      - client_auth_data:/data 

  client_sess_redis:
    image: redis:latest
    container_name: ${REDIS_CLIENT_SESS_DB}
    command: ["redis-server", "--port", "9369", "--appendonly", "yes"]
    volumes:
      - client_sess_data:/data

  caddy:
    image: caddy:latest
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - socketapp

volumes:
  app_agentik_data:
    external: true
  caddy_data:
    external: true
  caddy_config:
    external: true